name: Deploy GrantService

on:
  push:
    branches: [ main, Dev, master ]
  workflow_dispatch:

jobs:
  # Pre-deployment tests
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio psycopg2-binary python-dotenv
        pip install -r telegram-bot/requirements.txt || true

    - name: Run integration tests
      run: |
        # Run critical integration tests before deployment
        pytest tests/integration/test_full_application_flow.py::TestFullApplicationFlow::test_complete_application_flow -v || exit 1
        pytest tests/integration/test_streamlit_users_page.py::TestUsersPageData::test_get_total_users -v || exit 1
        pytest tests/integration/test_postgresql_migration.py::TestDatabaseConnection::test_can_connect_to_postgresql -v || exit 1
      continue-on-error: false

    - name: Notify tests failed
      if: failure()
      run: |
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=-4930683040" \
          -d "parse_mode=HTML" \
          -d "text=❌ <b>GrantService Tests FAILED</b>%0A%0ADeployment blocked - tests failed.%0ABranch: ${{ github.ref_name }}%0ACommit: ${{ github.sha }}%0A%0A<a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>View workflow run</a>"

  # Deployment job (only runs if tests pass)
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Notify deployment started
      run: |
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=-4930683040" \
          -d "parse_mode=HTML" \
          -d "text=🚀 <b>GrantService Deployment Started</b>%0A%0ABranch: ${{ github.ref_name }}%0ACommit: ${{ github.sha }}%0AAuthor: ${{ github.actor }}%0A%0ATests: ✅ Passed"

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || '22' }}
        script: |
          echo "Starting deployment..."
          
          # Остановка сервисов перед обновлением
          echo "Stopping services..."
          sudo systemctl stop grantservice-bot || true
          sudo systemctl stop grantservice-admin || true
          
          # Переход в директорию проекта
          cd /var/GrantService

          # ВАЖНО: Резервное копирование БД ПЕРЕД любыми git операциями
          echo "Backing up production database..."
          if [ -f "data/grantservice.db" ]; then
            cp data/grantservice.db data/grantservice.db.backup
            echo "✓ Database backed up to data/grantservice.db.backup"
          else
            echo "⚠ Warning: Production database not found at data/grantservice.db"
          fi

          # Защита критичных файлов конфигурации
          echo "Protecting config/.env (bot token)..."
          if [ -f "config/.env" ]; then
            cp config/.env /tmp/grantservice_env_safe
            echo "✓ Bot token backed up"
          else
            echo "⚠ Warning: config/.env not found - bot may fail to start!"
          fi

          # Защита директории data/ от git clean
          echo "Protecting data directory..."
          if [ -d "data" ]; then
            # Временно перемещаем data/ за пределы репозитория
            mv data /tmp/grantservice_data_safe
            echo "✓ Data directory moved to safe location"
          fi

          # Настройка git для работы без аутентификации
          git config pull.rebase false

          # Проверяем наличие локальных изменений
          echo "Checking for local changes..."
          if ! git diff-index --quiet HEAD --; then
            echo "⚠️  Local changes detected, will be overwritten"
            git status --short
          fi

          # Обновление из репозитория
          echo "Updating from GitHub..."
          git fetch --all

          # Определяем ветку и обновляемся из неё
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $BRANCH_NAME"

          # Безопасное обновление: сначала пробуем pull, при конфликтах - reset
          if [ "$BRANCH_NAME" = "master" ]; then
            echo "Updating to latest master..."
            if git merge-base --is-ancestor HEAD origin/master; then
              # Fast-forward возможен - безопасный pull
              git pull origin master
            else
              # Есть расхождения - нужен reset
              echo "⚠️  Diverged from origin, forcing reset..."
              git reset --hard origin/master
            fi
          else
            echo "Updating to latest Dev..."
            if git merge-base --is-ancestor HEAD origin/Dev; then
              git pull origin Dev
            else
              echo "⚠️  Diverged from origin, forcing reset..."
              git reset --hard origin/Dev
            fi
          fi

          # Очистка только ignored файлов (не трогаем untracked)
          git clean -fdX  # Только .pyc, __pycache__ и т.д.

          # ========================================
          # КРИТИЧЕСКАЯ ПРОВЕРКА: Verify critical files exist
          # ========================================
          echo "Verifying critical Python modules..."
          MISSING_FILES=0

          # Проверка data/database/ модулей
          if [ ! -f "data/database/__init__.py" ]; then
            echo "✗ ERROR: data/database/__init__.py is MISSING!"
            MISSING_FILES=1
          else
            echo "✓ data/database/__init__.py exists"
          fi

          if [ ! -f "data/database/models.py" ]; then
            echo "✗ ERROR: data/database/models.py is MISSING!"
            MISSING_FILES=1
          else
            echo "✓ data/database/models.py exists"
          fi

          if [ ! -f "data/database/auth.py" ]; then
            echo "✗ ERROR: data/database/auth.py is MISSING!"
            MISSING_FILES=1
          else
            echo "✓ data/database/auth.py exists"
          fi

          # Если файлы отсутствуют - восстанавливаем из git
          if [ $MISSING_FILES -eq 1 ]; then
            echo "⚠️  CRITICAL: Missing core Python modules detected!"
            echo "Restoring from git repository..."
            git restore data/database/

            # Повторная проверка
            if [ -f "data/database/models.py" ]; then
              echo "✓ Files successfully restored from git"
            else
              echo "✗ FATAL: Cannot restore critical files - deployment ABORTED"
              exit 1
            fi
          fi

          # Очистка Python кэша для чистого импорта
          echo "Clearing Python cache..."
          find . -type d -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true
          find . -type f -name '*.pyc' -delete 2>/dev/null || true
          echo "✓ Python cache cleared"

          # Восстановление data/ обратно
          echo "Restoring data directory..."
          if [ -d "/tmp/grantservice_data_safe" ]; then
            mv /tmp/grantservice_data_safe data
            echo "✓ Data directory restored"
          fi

          # Восстановление config/.env
          echo "Restoring config/.env (bot token)..."
          if [ -f "/tmp/grantservice_env_safe" ]; then
            mkdir -p config
            cp /tmp/grantservice_env_safe config/.env
            chmod 600 config/.env
            echo "✓ Bot token restored"
          fi

          # Проверяем, что обновление прошло успешно
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Updated to commit: $CURRENT_COMMIT"

          # Финальная проверка БД
          echo "Verifying production database..."
          if [ -f "data/grantservice.db" ]; then
            DB_SIZE=$(du -h data/grantservice.db | cut -f1)
            echo "✓ Production database intact: $DB_SIZE"
          else
            echo "✗ ERROR: Production database missing after update!"
            if [ -f "data/grantservice.db.backup" ]; then
              echo "Restoring from backup..."
              cp data/grantservice.db.backup data/grantservice.db
              echo "✓ Database restored from backup"
            fi
          fi
          
          # Проверка, что файлы обновлены
          echo "Checking if files are updated..."
          ls -la scripts/
          ls -la .github/workflows/
          
          # Активация виртуального окружения (если используется)
          if [ -f "/var/GrantService/venv/bin/activate" ]; then
              source /var/GrantService/venv/bin/activate
          fi
          
          # Обновление зависимостей для бота
          echo "Installing bot dependencies..."
          cd /var/GrantService/telegram-bot
          pip install -r requirements.txt
          
          # Обновление зависимостей для админки
          echo "Installing admin panel dependencies..."
          cd /var/GrantService/web-admin
          pip install -r requirements.txt
          
          # Инициализация авторизации (БЕЗОПАСНО для продакшн БД)
          echo "Initializing auth roles..."
          cd /var/GrantService
          python3 scripts/init_auth_roles.py || true
          python3 scripts/fix_authorization.py || true

          # Обновление systemd сервисов при необходимости
          echo "Updating systemd services if needed..."
          bash scripts/setup_systemd_services.sh || true
          
          # Запуск сервисов
          echo "Starting services..."
          sudo systemctl start grantservice-bot
          sudo systemctl start grantservice-admin
          
          # Небольшая пауза для запуска
          sleep 5
          
          # Проверка статуса
          echo "Checking service status..."
          sudo systemctl status grantservice-bot --no-pager
          sudo systemctl status grantservice-admin --no-pager

          echo "Deployment completed successfully!"

    # Post-deployment smoke tests
    - name: Run smoke tests
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || '22' }}
        script: |
          echo "Running smoke tests..."

          # Test 1: Check bot process is running
          if systemctl is-active --quiet grantservice-bot; then
            echo "✓ Bot service is running"
          else
            echo "✗ Bot service is NOT running"
            exit 1
          fi

          # Test 2: Check admin panel is running
          if systemctl is-active --quiet grantservice-admin; then
            echo "✓ Admin service is running"
          else
            echo "✗ Admin service is NOT running"
            exit 1
          fi

          # Test 3: Check admin panel HTTP endpoint
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8550/ || echo "000")
          if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "302" ]; then
            echo "✓ Admin panel HTTP: $HTTP_CODE"
          else
            echo "✗ Admin panel HTTP failed: $HTTP_CODE"
            exit 1
          fi

          # Test 4: Check HTTPS endpoint
          HTTPS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://grantservice.onff.ru/ || echo "000")
          if [ "$HTTPS_CODE" = "200" ] || [ "$HTTPS_CODE" = "302" ]; then
            echo "✓ HTTPS endpoint: $HTTPS_CODE"
          else
            echo "✗ HTTPS endpoint failed: $HTTPS_CODE"
            exit 1
          fi

          # Test 5: Check database connectivity
          cd /var/GrantService
          if python3 -c "from data.database.models import get_db_connection; conn = get_db_connection(); conn.close(); print('✓ Database connection OK')" 2>/dev/null; then
            echo "✓ Database is accessible"
          else
            echo "⚠ Database connection test failed (non-critical)"
          fi

          # Test 6: Check bot token is valid (not placeholder)
          if grep -q "YOUR_BOT_TOKEN" config/.env 2>/dev/null; then
            echo "✗ CRITICAL: Bot token is placeholder!"
            exit 1
          else
            echo "✓ Bot token is configured"
          fi

          echo "All smoke tests passed!"

    # Notify success
    - name: Notify deployment success
      if: success()
      run: |
        # Get commit message
        COMMIT_MSG=$(git log -1 --pretty=format:"%s")

        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=-4930683040" \
          -d "parse_mode=HTML" \
          -d "text=✅ <b>GrantService Deployment SUCCESS</b>%0A%0A📦 Branch: ${{ github.ref_name }}%0A💬 Commit: ${COMMIT_MSG}%0A👤 Author: ${{ github.actor }}%0A%0A🤖 Bot: Running%0A💻 Admin: Running%0A🌐 HTTPS: OK%0A%0A⏱ Deploy time: ~30s"

    # Notify failure and rollback
    - name: Rollback on failure
      if: failure()
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || '22' }}
        script: |
          echo "Deployment failed! Rolling back..."

          cd /var/GrantService

          # Get current and previous commit
          CURRENT_COMMIT=$(git rev-parse HEAD)
          PREVIOUS_COMMIT=$(git rev-parse HEAD~1)

          echo "Current commit: $CURRENT_COMMIT"
          echo "Rolling back to: $PREVIOUS_COMMIT"

          # Rollback to previous commit
          git reset --hard HEAD~1

          # Clear Python cache
          find . -type d -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true
          find . -type f -name '*.pyc' -delete 2>/dev/null || true

          # Restart services
          sudo systemctl restart grantservice-bot
          sudo systemctl restart grantservice-admin

          sleep 5

          # Check status after rollback
          if systemctl is-active --quiet grantservice-bot && systemctl is-active --quiet grantservice-admin; then
            echo "✓ Services restored after rollback"
          else
            echo "✗ Services still failing after rollback - manual intervention needed!"
            exit 1
          fi

    - name: Notify deployment failure
      if: failure()
      run: |
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=-4930683040" \
          -d "parse_mode=HTML" \
          -d "text=❌ <b>GrantService Deployment FAILED</b>%0A%0A⚠️ Automatic rollback executed%0A%0ABranch: ${{ github.ref_name }}%0ACommit: ${{ github.sha }}%0AAuthor: ${{ github.actor }}%0A%0A<a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>View logs</a>%0A%0A⚡️ Manual check required!"